spring:
  application:
    name: api-usuarios
  data:
    mongodb:
      uri: ${MONGO_URI}
  devtools:
    restart:
      enabled: true

server:
  port: ${PORT:8084}
  servlet:
    context-path: /api/usuarios
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}


apis-net:
  token: ${API_NET_TOKEN}
  url: ${API_NET_URL}

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  phone_number: ${TWILIO_PHONE_NUMBER}
  templates:
    validar_cuenta: ${TWILIO_TEMPLATE_VALIDAR_CUENTA}