spring:
  application:
    name: api-usuarios
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/proyectoBC}
  devtools:
    restart:
      enabled: true

server:
  port: ${PORT:8084}
  servlet:
    context-path: /api/usuarios
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


apis-net:
  token: ${API_NET_TOKEN:apis-token-6776.OLyGllM8ov0NcyjYCy4V84SKbxnL3Ix9}
  url: ${API_NET_URL:https://api.apis.net.pe/v2/reniec/dni}

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID:ACc44ab6936281f296af497c0a360787dd}
  auth_token: ${TWILIO_AUTH_TOKEN:b71e2235c478a173950458104e159110}
  phone_number: ${TWILIO_PHONE_NUMBER:+14155238886}
  templates:
    validar_cuenta: ${TWILIO_TEMPLATE_VALIDAR_CUENTA:HX319225d7f8d5f8a5d8ad796edbfad867}