spring:
  application:
    name: api-productos
  data:
    mongodb:
      uri: mongodb://localhost:27017

server:
  port: ${PORT:0}
  servlet:
    context-path: /api/productos

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka