spring:
  application:
    name: api-compras
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyectoBC
  devtools:
    restart:
      enabled: true

server:
  port: ${PORT:8081}
  servlet:
    context-path: /api/compras
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
