spring:
  application:
    name: api-compras
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyectoBC
  devtools:
    restart:
      enabled: true

server:
  port: ${PORT:0}
  servlet:
    context-path: /api/compras
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.miapp.paquete: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  openapi:
    groups:
      - group1:
          paths-to-match: /api/compras/**
          packages-to-scan: com.miapp.paquete.compras
          title: Compras
          description: Servicios para la gestión de compras
          version: 1.0.0
          contact:
            name: MiApp
            email: