spring:
  application:
    name: microservicio-eureka-server
  cloud:
    config:
      import-check:
        enabled: false
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.miapp.paquete: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


