spring:
  application:
    name: api-notificaciones
  sendgrid:
    api-key: "TU_API_KEY_DE_SENDGRID"
server:
  port: ${PORT:0}
  servlet:
    context-path: /api/notificaciones

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
